        !COMPILER-GENERATED INTERFACE MODULE: Sat Sep 14 11:16:36 2019
        MODULE TEST01_mod
          INTERFACE 
            SUBROUTINE TEST01
            END SUBROUTINE TEST01
          END INTERFACE 
        END MODULE TEST01_mod
